In [1]:
from google.colab import files
uploaded = files.upload()

Saving urls_1.csv to urls_1.csv

In [2]:
import pandas as pd
df=pd.read_csv('urls_1.csv',encoding='latin-1')

In [3]:
df.columns

Index(['url', 'label', 'dots', 'at', 'equals', 'slashes', 'hyphens', 'colons',
       'question_marks', 'digits', 'and', 'underscore', 'tilde', 'percent',
       'lowercase', 'uppercase', 'upper_to_lower_ratio', 'is_https',
       'url_length', 'domain_length', 'path_length', 'path_depth',
       'query_length', 'query_count', 'fragment_length', 'se_url', 'se_domain',
       'se_path', 'se_query', 'se_fragment', 'cte_domain', 'is_domain_ip',
       'tld', 'is_tld_iana_reg', 'is_mtld', 'subdomains', 'special_chars',
       'digit_to_length_ratio', 'char_to_length_ratio',
       'specialchar_to_length_ratio'],
      dtype='object')

In [4]:
df.head()

,url,label,dots,at,equals,slashes,hyphens,colons,question_marks,digits,...,cte_domain,is_domain_ip,tld,is_tld_iana_reg,is_mtld,subdomains,special_chars,digit_to_length_ratio,char_to_length_ratio,specialchar_to_length_ratio
0,http://www.srilankan.com/en_uk/special-offers/...,0,2,0,4,5,5,1,1,23,...,3.75,0,com,1,0,1,6,0.10,0.73,0.03
1,https://www.vismaspcs.se/visma-support/visma-a...,0,3,0,0,7,6,1,0,4,...,3.77,0,se,1,0,1,0,0.03,0.85,0.00
2,https://www.mclarenstore.com/stores/mclaren/en...,0,2,0,0,7,0,1,0,0,...,4.04,0,com,1,0,1,0,0.00,0.82,0.00
3,http://eu.battle.net.blizzardenteaitaccoutmana...,1,5,0,0,3,0,1,0,2,...,5.45,0,com,1,0,3,0,0.03,0.83,0.00
4,http://ww0.chase.com.asp72.com/ccp/clientconfi...,1,5,0,1,5,0,1,1,5,...,3.97,0,com,1,0,3,0,0.06,0.79,0.00

In [5]:
df=df[['url','label']]

In [6]:
df.head()

                                                 url  label
0  http://www.srilankan.com/en_uk/special-offers/...      0
1  https://www.vismaspcs.se/visma-support/visma-a...      0
2  https://www.mclarenstore.com/stores/mclaren/en...      0
3  http://eu.battle.net.blizzardenteaitaccoutmana...      1
4  http://ww0.chase.com.asp72.com/ccp/clientconfi...      1

In [7]:
df.shape

(100000, 2)

In [8]:
df.isnull().sum()

url      0
label    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
#Feature Engineering
df['url_length']=df['url'].apply(len)

In [11]:
df

                                                     url  label  url_length
0      http://www.srilankan.com/en_uk/special-offers/...      0         231
1      https://www.vismaspcs.se/visma-support/visma-a...      0         136
2      https://www.mclarenstore.com/stores/mclaren/en...      0          55
3      http://eu.battle.net.blizzardenteaitaccoutmana...      1          64
4      http://ww0.chase.com.asp72.com/ccp/clientconfi...      1          87
...                                                  ...    ...         ...
99995  http://www.ooyala.com/videomind/categories/ooy...      0          54
99996  http://www.website.informer.com/omnivox.colleg...      0          61
99997  http://www.vradlaw.com/www.paypal.co.uk1/encri...      1          72
99998  https://www.arukereso.hu/jatekprogram-c3255/f:...      0          68
99999  http://www.diamonddavesrecycling.com/includes/...      1          59

[100000 rows x 3 columns]

In [12]:
df['has_https']=df['url'].apply(
    lambda x:1 if 'https' in x else 0
)

In [13]:
df.head()

,url,label,url_length,has_https
0,http://www.srilankan.com/en_uk/special-offers/...,0,231,0
1,https://www.vismaspcs.se/visma-support/visma-a...,0,136,1
2,https://www.mclarenstore.com/stores/mclaren/en...,0,55,1
3,http://eu.battle.net.blizzardenteaitaccoutmana...,1,64,0
4,http://ww0.chase.com.asp72.com/ccp/clientconfi...,1,87,0

In [14]:
df['num_dots']=df['url'].apply(
    lambda x: x.count('.')
)

In [15]:
df.head()

,url,label,url_length,has_https,num_dots
0,http://www.srilankan.com/en_uk/special-offers/...,0,231,0,2
1,https://www.vismaspcs.se/visma-support/visma-a...,0,136,1,3
2,https://www.mclarenstore.com/stores/mclaren/en...,0,55,1,2
3,http://eu.battle.net.blizzardenteaitaccoutmana...,1,64,0,5
4,http://ww0.chase.com.asp72.com/ccp/clientconfi...,1,87,0,5

In [16]:
df['has_at'] = df['url'].apply(
    lambda x: 1 if '@' in x else 0
)

In [17]:
df['num_hyphens'] = df['url'].apply(
    lambda x: x.count('-')
)

In [18]:
df['num_slash'] = df['url'].apply(
    lambda x: x.count('/')
)

In [19]:
df.head()

,url,label,url_length,has_https,num_dots,has_at,num_hyphens,num_slash
0,http://www.srilankan.com/en_uk/special-offers/...,0,231,0,2,0,5,5
1,https://www.vismaspcs.se/visma-support/visma-a...,0,136,1,3,0,6,7
2,https://www.mclarenstore.com/stores/mclaren/en...,0,55,1,2,0,0,7
3,http://eu.battle.net.blizzardenteaitaccoutmana...,1,64,0,5,0,0,3
4,http://ww0.chase.com.asp72.com/ccp/clientconfi...,1,87,0,5,0,0,5

In [20]:
X = df[['url_length',
        'has_https',
        'num_dots',
        'has_at',
        'num_hyphens',
        'num_slash']]

y = df['label']

In [21]:
X.head()

   url_length  has_https  num_dots  has_at  num_hyphens  num_slash
0         231          0         2       0            5          5
1         136          1         3       0            6          7
2          55          1         2       0            0          7
3          64          0         5       0            0          3
4          87          0         5       0            0          5

In [22]:
y.head()

0    0
1    0
2    0
3    1
4    1
Name: label, dtype: int64

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [24]:
X_train.shape

(80000, 6)

In [25]:
X_test.shape

(20000, 6)

In [26]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [27]:
y_pred = model.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.8314

In [29]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.81      0.84     11048
           1       0.79      0.86      0.82      8952

    accuracy                           0.83     20000
   macro avg       0.83      0.83      0.83     20000
weighted avg       0.84      0.83      0.83     20000

In [30]:
import pandas as pd

importance = model.feature_importances_

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importance
})

feature_importance.sort_values(
    by='Importance',
    ascending=False
)

       Feature  Importance
1    has_https    0.457609
0   url_length    0.227869
2     num_dots    0.130770
4  num_hyphens    0.118641
5    num_slash    0.061592
3       has_at    0.003519

In [31]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)
from sklearn.metrics import accuracy_score

accuracy_score(y_test, lr_pred)

0.8377

In [32]:
from sklearn.metrics import classification_report

print(classification_report(y_test, lr_pred))

              precision    recall  f1-score   support

           0       0.91      0.78      0.84     11048
           1       0.77      0.91      0.83      8952

    accuracy                           0.84     20000
   macro avg       0.84      0.84      0.84     20000
weighted avg       0.85      0.84      0.84     20000

In [33]:
from sklearn.svm import SVC

In [34]:
svm_model = SVC()

In [35]:
svm_model.fit(X_train, y_train)

SVC()

In [37]:
svm_pred = svm_model.predict(X_test)

In [38]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, svm_pred)

0.82585